### ISSUE TITLE
$EventUri is incorrect when this app is used as notification channel

### ISSUE THREAD

**Issue by Ahmad-anility** [datalust/seq-app-opsgenie#14]
After configuring the app in SEQ when we test it using the events explores -> Send to app the link in the body of opsgenie is correct and clicking on the link correctly opens the event. However when we use this app in the alert as notification channel the event uri is incorrect and the event id does not match what triggered the event.

**Comment by nblumhardt** [comment]
Hi Ahmad, thanks for raising this.

`$EventUri` is only populated correctly when the incoming event corresponds to one in the event stream.

For alerts, `$Properties.Alert.Url` property should be the correct alternative. Unfortunately I'm a little rusty on Handlebars syntax and don't have an Opsgenie instance to test this out against.

If the above doesn't work, we might need to make some modifications to the app to deal with this - perhaps using the alert URL as the value of `$EventUri` if it's present.

Let me know if this helps!

Best regards,
Nick

**Comment by Ahmad-anility** [comment]
Thanks @nblumhardt, we used Alert Url instead and from there we can explore the query 

Much appreciated
Ahmad
